# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '\.json$'
      - id: check-yaml
        exclude: ^.*\/cloudformation\/.*
      - id: check-added-large-files

  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.15.0 # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: cf/.*\.(json|yml|yaml)$

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-isort]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.38.0 # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: yarn prettier --write --list-different --ignore-path
        language: system
        files: .*\.(ts|tsx|js|jsx|json|yml|yaml|md)
