name: CI

on:
  pull_request:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**", "README*" ]

  push:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**", "README*" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            requirements.txt

      - run: pip install -r requirements.txt

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

      - name: Unit Test
        env:
          DEFAULT_REGION: ap-northeast-1
          AWS_ACCOUNT_ID: "000000000000"
          AWS_ACCESS_KEY_ID: dummy-access-key
          AWS_SECRET_ACCESS_KEY: dummy-secret-key
          AWS_ENDPOINT_URL: "http://localhost:4566"
        run: |
          docker-compose -f docker-compose.ci.yml up -d
          cd lambda && pytest
